spring:
  #mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.130/sell?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console:  "%d - %msg%n"
server:
  servlet:
    context-path: /sell
#  path: /var/log/tomcat